### PR TITLE
JWT Setup for Authentication

### LINKED ISSUE #1: User Authentication ( JWT Token )
***set up devise-jwt, use curl to ensure session requests can be made, make a change only logged in users could make***

### PR DESCRIPTION
**Pull request by xihai01**
### What github issue is this PR for, if any?
Resolves #1 #2 

### What changed, and why?
Set up JWT with Devise.
I had to extend Devise sessions controller's **create** action to return a custom response for JSON requests.
I also extend **respond_to_on_destroy** method so sign out responds in json.
Additionally, I had to modify the **accessible** module so JSON requests don't get redirected to the root path.

### How is this tested? (please write tests!) 💖💪
I created **request** specs for good/bad login to verify correct headers were sent (e.x authorization, content-type...etc) and also JSON data.
I also made specs for the sign out route -> testing JWT is moved to denylist and a 200 response.
Postman was used to make changes (i.e unassign a case assignment) in the portal provided a JWT was present.
I also did a live test where I ran the rails server on a ngrok tunnel and frontend app using expo go side by side.
See screenshots below.

#### Live test using Ngrok and my android phone running the frontend with Expo go.
Screenshot from 2023-05-09 15-30-18

https://github.com/ctc-casa-ios/api/assets/86758440/1c15c9fa-a6df-4450-bf8e-496df232d859

#### Postman: Success login means auth JWT in header
Screenshot from 2023-05-09 15-44-40
Screenshot from 2023-05-09 15-45-05

#### Postman: Failed login means auth JWT not in header
Screenshot from 2023-05-09 15-45-22
Screenshot from 2023-05-09 15-45-31

#### Postman: Unassign a case assignment using auth token passed in request header
Screenshot from 2023-05-09 17-12-06

#### Postman: Unassign a case assignment with no auth token 
Screenshot from 2023-05-09 17-12-28

#### Postman: Sign out returns 200 response + JWT is moved to denylist
Screenshot from 2023-05-10 18-27-39
Screenshot from 2023-05-10 18-27-22

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
alt text

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by xihai01** [comment]
I think this is good to go

**Review by 7riumph — APPROVED** [review]
🔥🔥🔥

**Comment by xihai01** [comment]
Feel free to merge when ready! I don't have access to this repo.

**Comment by xihai01** [comment]
~we also need to ask casa how to store credentials.~
nvm, I figured out how. Secrets can be stored in the credentials.yml files.
3 separate cred files exists depending on the environment: test, dev, production.

`EDITOR=nano bin/rails credentials:edit --environment development`

**Pull request merged**
